### ISSUE TITLE
issues with single news

### ISSUE THREAD

**Issue by vincent3569** [acrylian/swipe_gestures#4]
hi

there are 2 issues:
- line 92, it should be a } rather than a {
- getPrevNewsURL and getNextNewsURL return an array with title and titlelink
(see http://www.zenphoto.org/documentation/plugins/zenpage/_zp-extensions---zenpage---zenpage-template-functions.php.html#functiongetPrevNewsURL)

**Comment by acrylian** [comment]
Good catch somehow forgot that those functions are a bit off returning arrays somehow. That is counterintuitive actually and probably should be changed someday…

**Comment by vincent3569** [comment]
hi malte,
the 1st issue is not fixed : line 92, it should be a } rather than a {

**Comment by acrylian** [comment]
I am apparently blind…  Thanks.
